dofile(minetest.get_modpath("mycastle").."/stonebrick.lua")
dofile(minetest.get_modpath("mycastle").."/castle.lua")
dofile(minetest.get_modpath("mycastle").."/doors.lua")
dofile(minetest.get_modpath("mycastle").."/furniture.lua")
dofile(minetest.get_modpath("mycastle").."/chest.lua")
dofile(minetest.get_modpath("mycastle").."/fakelava.lua")
